import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { canonicalSha256, fileSha256 } from '../../../04_AI_Work_Environment/Source_Resolution/scripts/source-resolution.mjs';
import { finalReviewIdentity } from '../scripts/final-review-package-compiler.mjs';
import { buildPublicationBundle, createDeterministicZip, explicitPublicationIntent, publicationBundleIdentity, publicationConditionsIdentity, publicationE2EPlan, publicationZipE2EPlan, validateApprovedPackageBinding, validateG5, validatePublicationStep, verifyBundleDirectory, verifyBundleZip } from '../scripts/publication-runtime.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PS_BUNDLE = path.resolve(HERE, '../scripts/PublicationBundle.psm1');
const PS_APPROVAL = path.resolve(HERE, '../scripts/PublicationApproval.psm1');
const PS_HANDOFF = path.resolve(HERE, '../scripts/Test-PublicationBundleHandoff.ps1');
const EXISTING_AIDAILY_006_PACKAGE = 'FRP-AIDAILY-006-bec6d699fc80d6acc54a037366ec8acb691f350fbda679ccf7a76e3966628c26';
const clone = (value) => structuredClone(value);
const q = (value) => `'${String(value).replaceAll("'", "''")}'`;
async function writeJson(file, value) { await fs.writeFile(file, JSON.stringify(value, null, 2)); return file; }

async function fixture(articleId = 'AIDAILY-TEST') {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'publication-runtime-'));
  const body = path.join(root, 'D3.md'); const header = path.join(root, 'header.png'); const source = path.join(root, 'source-manifest.json');
  await fs.writeFile(body, 'Final D3 body bytes'); await fs.writeFile(header, Buffer.from([1,2,3,4,5,6])); await fs.writeFile(source, '{"schema_version":"source-manifest/v2","result":"PASS"}');
  const destination = {service:'note',account_id:'miku_inada',publication_target:`article/${articleId}`};
  const packageValue = {
    schema_version:'note-final-review-package/v3',compiler_version:'note-final-review-package-compiler/v2',package_id:'',identity_sha256:'',state:'READY_FOR_FINAL_REVIEW',article_id:articleId,title:'Final title',
    d3_body:{artifact_id:`${articleId}-D3`,file:`private://${articleId}/D3.md`,sha256:await fileSha256(body),content:'Final D3 body bytes'},
    marketing_review:{status:'PASS',identity:'MR-TEST-v3',version:'v3',evidence:{artifact_id:'MR-EVIDENCE',file:'private://marketing.json',sha256:'1'.repeat(64)}},
    header:{asset_id:`FHA-${articleId}-${'a'.repeat(64)}`,display_title:'Final title',formal_asset_state:'FORMAL_HEADER_ASSET',formal_asset_identity_sha256:'a'.repeat(64),file:`archive://${articleId}/header.png`,sha256:await fileSha256(header),master_template:{asset_id:'NOTE-HEADER-MASTER-v1.0',version:'v1.0',canonical_locator:'04_AI_Work_Environment/Visual_Production/assets/NOTE_HEADER_MASTER_TEMPLATE_v1.0.png',sha256:'b'.repeat(64)},route_evidence:{implementation_id:'repo-skill:visual-production-bridge/cloud-work-v2',route:'repository-cloud-work-request-bound',runtime_receipt_sha256:'c'.repeat(64)},asset_qa:{status:'PASS',evidence:{artifact_id:'HEADER-QA',file:'archive://header-qa.json',sha256:'2'.repeat(64)}},human_approval:{event_id:'HE-HEADER',evidence_sha256:'d'.repeat(64)}},
    publication_conditions:{access_boundary:{mode:'MEMBERSHIP',free_end_marker:'free ends here',membership_start_marker:'membership starts here'},membership:{enabled:true,name:'AIとの日常',plan:'AIとの日常'},magazine:{enabled:true,name:'AIとの日常'},price:{currency:'JPY',amount:1500},tags:['AI活用','note','働き方','AIとの日常'],other_conditions:['standard-membership-cta']},
    destination,purpose:'NOTE_PUBLICATION',source_manifest:{manifest_id:'SM-TEST-D3',file:`private://${articleId}/source-manifest.json`,sha256:await fileSha256(source)},approval:{status:'PENDING'}
  };
  Object.assign(packageValue, finalReviewIdentity(packageValue));
  const packagePath=await writeJson(path.join(root,'package.json'),packageValue); const packageSha=await fileSha256(packagePath);
  const event={schema_version:'note-human-event/v2',event_id:'HE-TEST-001',actor_type:'human',evidence_origin:'human-response-event',occurred_at:'2026-09-07T01:01:00+09:00',statement:'OK投稿して',context:{stage:'FINAL_REVIEW_PACKAGE_PRESENTED',presented_at:'2026-09-07T01:00:00+09:00',package_id:packageValue.package_id,package_identity_sha256:packageValue.identity_sha256,package_sha256:packageSha,destination,purpose:'NOTE_PUBLICATION'}};
  const eventPath=await writeJson(path.join(root,'human-event.json'),event);
  const approval={schema_version:'note-publication-approval/v2',approval_id:'PA-TEST-001',approval_scope:'NOTE_PUBLICATION',approval_type:'FINAL_AND_PUBLICATION',decision:'APPROVED',package_id:packageValue.package_id,package_identity_sha256:packageValue.identity_sha256,package_sha256:packageSha,human_event_id:event.event_id,human_event_sha256:await fileSha256(eventPath),destination,purpose:'NOTE_PUBLICATION',approved_at:event.occurred_at};
  const approvalPath=await writeJson(path.join(root,'approval.json'),approval);
  return {root,body,header,source,packagePath,eventPath,approvalPath,packageValue,event,approval,builder:{packagePath,humanEventPath:eventPath,approvalPath,sourceManifestPath:source,d3BodyPath:body,headerPath:header}};
}

async function mutateBundle(built, label) { const root=await fs.mkdtemp(path.join(os.tmpdir(),`publication-mutation-${label}-`)); const bundle=path.join(root,'PublicationBundle'); await fs.cp(built.bundle_directory,bundle,{recursive:true}); return {root,bundle}; }
async function repairManifest(bundle, mutator=()=>{}) { const file=path.join(bundle,'manifest.json'); const manifest=JSON.parse(await fs.readFile(file,'utf8')); mutator(manifest); Object.assign(manifest,publicationBundleIdentity(manifest)); delete manifest.canonical_identity_json; delete manifest.safe_article_id; await writeJson(file,manifest); }
async function mustFail(action, pattern) { await assert.rejects(action,pattern); }

test('Cloud Work Publication runtime parity, acceptance, and negative cases', async (t) => {
  const f=await fixture(); const built=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'bundles')});

  await t.test('AIDAILY-006 existing v3/v2 contract and exact OK投稿して intent remain reusable', async()=>{assert.match(EXISTING_AIDAILY_006_PACKAGE,/^FRP-AIDAILY-006-[0-9a-f]{64}$/);assert.equal(explicitPublicationIntent('OK投稿して','FINAL_REVIEW_PACKAGE_PRESENTED'),true);assert.equal(explicitPublicationIntent('OK投稿して','HUMAN_REVIEW'),false);});
  await t.test('Cloud-only approved Package builds and seals without PowerShell', async()=>{assert.equal(built.state,'BUNDLE_SEALED');assert.equal(built.handoff_state,'HANDOFF_PENDING');});
  await t.test('same Work directory reaches HANDOFF_VERIFIED and G5', async()=>{const handoff=await verifyBundleDirectory({bundleDirectory:built.bundle_directory,expectedPackageId:f.packageValue.package_id});assert.equal(handoff.state,'HANDOFF_VERIFIED');const g5=await validateG5({bundleDirectory:built.bundle_directory,expectedPackageId:f.packageValue.package_id});assert.equal(g5.state,'G5_PASS');});
  await t.test('unchanged Package runs G5 through PPV with no new Human approval', async()=>{const plan=await publicationE2EPlan({bundleDirectory:built.bundle_directory,expectedPackageId:f.packageValue.package_id});assert.deepEqual(plan.states,['HANDOFF_VERIFIED','G5_PASS','NOTE_DRAFT_CREATE','BODY_APPLY','HEADER_APPLY','PUBLICATION_CONDITIONS_APPLY','SETTINGS_VERIFY','PUBLISHED','PPV_PASS']);assert.equal(plan.requires_additional_human_approval,false);assert.equal(plan.browser_handoff.state,'READY_FOR_CLOUD_BROWSER');});
  await t.test('same inputs produce identical logical identity, manifest, conditions, and ZIP bytes', async()=>{const second=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'bundles-two')});assert.equal(second.bundle_id,built.bundle_id);for(const name of ['manifest.json','publication-conditions.json'])assert.equal(await fileSha256(path.join(second.bundle_directory,name)),await fileSha256(path.join(built.bundle_directory,name)));assert.equal(await fileSha256(second.zip_path),await fileSha256(built.zip_path));});
  await t.test('single ZIP handoff verifies in Node', async()=>{const received=await verifyBundleZip({zipPath:built.zip_path,expectedPackageId:f.packageValue.package_id,extractionDirectory:path.join(f.root,'received')});assert.equal(received.state,'HANDOFF_VERIFIED');assert.equal(received.transport,'single_zip');});
  await t.test('single ZIP handoff reaches the same G5 through PPV plan', async()=>{const plan=await publicationZipE2EPlan({zipPath:built.zip_path,expectedPackageId:f.packageValue.package_id,extractionDirectory:path.join(f.root,'received-e2e')});assert.equal(plan.states.at(-1),'PPV_PASS');assert.equal(plan.transport,'single_zip');assert.equal(plan.requires_additional_human_approval,false);});
  await t.test('Cloud CLI entrypoint reaches READY_FOR_CLOUD_BROWSER without PowerShell', async()=>{const output=execFileSync(process.execPath,[path.resolve(HERE,'../scripts/publication-runtime.mjs'),'e2e','--bundle-directory',built.bundle_directory,'--expected-package-id',f.packageValue.package_id],{encoding:'utf8'});const plan=JSON.parse(output);assert.equal(plan.result,'PASS');assert.equal(plan.browser_handoff.state,'READY_FOR_CLOUD_BROWSER');});
  await t.test('Human Event chronology is validated', async()=>{const event=clone(f.event);event.occurred_at='2026-09-07T00:59:59+09:00';const eventPath=await writeJson(path.join(f.root,'event-before-presentation.json'),event);const approval=clone(f.approval);approval.human_event_sha256=await fileSha256(eventPath);approval.approved_at=event.occurred_at;const approvalPath=await writeJson(path.join(f.root,'approval-before-presentation.json'),approval);await mustFail(()=>validateApprovedPackageBinding({...f.builder,actualPackagePath:f.packagePath,humanEventPath:eventPath,approvalPath}),/HUMAN_EVENT_BEFORE_FINAL_PACKAGE/);});
  await t.test('actual Package bytes and identity are bound', async()=>{const actual=clone(f.packageValue);actual.title='different title';const actualPath=await writeJson(path.join(f.root,'actual-package-tampered.json'),actual);await mustFail(()=>validateApprovedPackageBinding({...f.builder,actualPackagePath:actualPath}),/ACTUAL_PACKAGE_MISMATCH|FINAL_REVIEW_PACKAGE_IDENTITY_MISMATCH/);});
  await t.test('D3 body tamper fails', async()=>{const m=await mutateBundle(built,'body');await fs.writeFile(path.join(m.bundle,'body.md'),'tampered');await mustFail(()=>verifyBundleDirectory({bundleDirectory:m.bundle,expectedPackageId:f.packageValue.package_id}),/BODY_SHA_MISMATCH/);});
  await t.test('Header tamper fails', async()=>{const m=await mutateBundle(built,'header');await fs.writeFile(path.join(m.bundle,'header.png'),Buffer.from([9,9]));await mustFail(()=>verifyBundleDirectory({bundleDirectory:m.bundle,expectedPackageId:f.packageValue.package_id}),/HEADER_SHA_MISMATCH/);});
  await t.test('Publication Conditions and free boundary tamper fails even after manifest repair', async()=>{const m=await mutateBundle(built,'conditions');const p=path.join(m.bundle,'publication-conditions.json');const c=JSON.parse(await fs.readFile(p,'utf8'));c.conditions.access_boundary.free_end_marker='changed';const ci=publicationConditionsIdentity(c.conditions);c.identity_sha256=ci.identity_sha256;await writeJson(p,c);await repairManifest(m.bundle,async()=>{});const manifest=JSON.parse(await fs.readFile(path.join(m.bundle,'manifest.json'),'utf8'));manifest.publication_conditions.sha256=await fileSha256(p);manifest.publication_conditions.identity_sha256=ci.identity_sha256;Object.assign(manifest,publicationBundleIdentity(manifest));delete manifest.canonical_identity_json;delete manifest.safe_article_id;await writeJson(path.join(m.bundle,'manifest.json'),manifest);await mustFail(()=>verifyBundleDirectory({bundleDirectory:m.bundle,expectedPackageId:f.packageValue.package_id}),/PUBLICATION_CONDITIONS_PACKAGE_MISMATCH/);});
  await t.test('Source Manifest tamper fails after outer identity repair', async()=>{const m=await mutateBundle(built,'source');const p=path.join(m.bundle,'source-manifest.json');await fs.writeFile(p,'changed');await repairManifest(m.bundle,(manifest)=>{manifest.source_manifest.sha256=canonicalSha256('placeholder');});const manifest=JSON.parse(await fs.readFile(path.join(m.bundle,'manifest.json'),'utf8'));manifest.source_manifest.sha256=await fileSha256(p);Object.assign(manifest,publicationBundleIdentity(manifest));delete manifest.canonical_identity_json;delete manifest.safe_article_id;await writeJson(path.join(m.bundle,'manifest.json'),manifest);await mustFail(()=>verifyBundleDirectory({bundleDirectory:m.bundle,expectedPackageId:f.packageValue.package_id}),/SOURCE_MANIFEST_PACKAGE_MISMATCH/);});
  await t.test('Approval Evidence and Human Event tamper fail', async()=>{for(const name of ['approval-evidence.json','human-event.json']){const m=await mutateBundle(built,name);await fs.appendFile(path.join(m.bundle,name),' ');await mustFail(()=>verifyBundleDirectory({bundleDirectory:m.bundle,expectedPackageId:f.packageValue.package_id}),new RegExp(name.startsWith('approval')?'APPROVAL_EVIDENCE_SHA_MISMATCH':'HUMAN_EVENT_SHA_MISMATCH'));}});
  await t.test('destination, purpose, and approval scope reuse fail', async()=>{const badApproval=clone(f.approval);badApproval.approval_scope='GIT_PUSH';const bad=await writeJson(path.join(f.root,'bad-scope.json'),badApproval);await mustFail(()=>validateApprovedPackageBinding({...f.builder,actualPackagePath:f.packagePath,approvalPath:bad}),/APPROVAL_SCHEMA_FAIL|APPROVAL_SCOPE_MISMATCH/);const m=await mutateBundle(built,'destination');await repairManifest(m.bundle,(manifest)=>{manifest.destination.account_id='other';});await mustFail(()=>verifyBundleDirectory({bundleDirectory:m.bundle,expectedPackageId:f.packageValue.package_id}),/BUNDLE_DESTINATION_PURPOSE_MISMATCH|DESTINATION_MISMATCH/);});
  await t.test('missing, extra, and nested files fail', async()=>{const missing=await mutateBundle(built,'missing');await fs.rm(path.join(missing.bundle,'body.md'));await mustFail(()=>verifyBundleDirectory({bundleDirectory:missing.bundle,expectedPackageId:f.packageValue.package_id}),/BUNDLE_FILE_MISSING/);const extra=await mutateBundle(built,'extra');await fs.writeFile(path.join(extra.bundle,'extra.txt'),'x');await mustFail(()=>verifyBundleDirectory({bundleDirectory:extra.bundle,expectedPackageId:f.packageValue.package_id}),/BUNDLE_UNEXPECTED_FILE/);const nested=await mutateBundle(built,'nested');await fs.mkdir(path.join(nested.bundle,'nested'));await mustFail(()=>verifyBundleDirectory({bundleDirectory:nested.bundle,expectedPackageId:f.packageValue.package_id}),/BUNDLE_UNEXPECTED_DIRECTORY/);});
  await t.test('ZIP path escape fails before extraction', async()=>{const evil=path.join(f.root,'evil.zip');const safe='PublicationBundle/body.md';const unsafe='../'+'x'.repeat(Buffer.byteLength(safe)-3);await createDeterministicZip(evil,[{name:safe,data:Buffer.from('x')}]);const bytes=await fs.readFile(evil);let replaced=0;for(let at=bytes.indexOf(Buffer.from(safe));at>=0;at=bytes.indexOf(Buffer.from(safe),at+unsafe.length)){Buffer.from(unsafe).copy(bytes,at);replaced+=1;}assert.equal(replaced,2);await fs.writeFile(evil,bytes);await mustFail(()=>verifyBundleZip({zipPath:evil,expectedPackageId:f.packageValue.package_id,extractionDirectory:path.join(f.root,'evil-out')}),/BUNDLE_ZIP_PATH_ESCAPE/);});
  await t.test('sealed Bundle modification cannot be reused', async()=>{await fs.appendFile(path.join(built.bundle_directory,'body.md'),'x');await mustFail(()=>buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'bundles')}),/BUNDLE_IMMUTABLE_CONFLICT|BUNDLE_HANDOFF_FAIL/);});
  await t.test('redundant approval request and new Human decision both stop', async()=>{const third=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'bundles-three')});const fourth=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'bundles-four')});await mustFail(()=>validatePublicationStep({step:'PUBLISH',bundleDirectory:third.bundle_directory,expectedPackageId:f.packageValue.package_id,additionalHumanApprovalRequested:true}),/REDUNDANT_PUBLICATION_APPROVAL_REQUEST/);await mustFail(()=>validatePublicationStep({step:'PUBLISH',bundleDirectory:fourth.bundle_directory,expectedPackageId:f.packageValue.package_id,newHumanDecisionRequired:true}),/APPROVAL_INVALIDATED_NEW_HUMAN_DECISION/);});
  await t.test('PowerShell and Node calculate identical Conditions and Bundle identities', async()=>{const clean=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'parity')});const manifestPath=path.join(clean.bundle_directory,'manifest.json');const conditionsPath=path.join(clean.bundle_directory,'publication-conditions.json');const script=`Import-Module ${q(PS_BUNDLE)} -Force; Import-Module ${q(PS_APPROVAL)} -Force; $m=Get-Content -Raw -LiteralPath ${q(manifestPath)}|ConvertFrom-Json -Depth 50; $c=Get-Content -Raw -LiteralPath ${q(conditionsPath)}|ConvertFrom-Json -Depth 50; [pscustomobject]@{bundle=(PublicationBundle\\Get-NotePublicationBundleIdentity $m).identity_sha256;conditions=(PublicationBundle\\Get-NotePublicationConditionsIdentity $c.conditions).identity_sha256;intent=(Test-NoteExplicitPublicationIntent -Statement 'OK投稿して' -Stage 'FINAL_REVIEW_PACKAGE_PRESENTED')}|ConvertTo-Json -Compress`;const parity=JSON.parse(execFileSync('pwsh',['-NoProfile','-Command',script],{encoding:'utf8'}));assert.equal(parity.bundle,JSON.parse(await fs.readFile(manifestPath,'utf8')).identity_sha256);assert.equal(parity.conditions,JSON.parse(await fs.readFile(conditionsPath,'utf8')).identity_sha256);assert.equal(parity.intent,true);});
  await t.test('PowerShell-built Bundle has the same identity and logical bytes and verifies in Node', async()=>{const nodeBuild=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'node-parity')});const psOutput=path.join(f.root,'ps-build');const script=`Import-Module ${q(PS_BUNDLE)} -Force; PublicationBundle\\New-NotePublicationBundle -PackagePath ${q(f.packagePath)} -HumanEventPath ${q(f.eventPath)} -ApprovalPath ${q(f.approvalPath)} -SourceManifestPath ${q(f.source)} -D3BodyPath ${q(f.body)} -HeaderPath ${q(f.header)} -OutputDirectory ${q(psOutput)} | ConvertTo-Json -Compress`;const psBuild=JSON.parse(execFileSync('pwsh',['-NoProfile','-Command',script],{encoding:'utf8'}));assert.equal(psBuild.bundle_id,nodeBuild.bundle_id);for(const name of ['approval-evidence.json','body.md','final-review-package.json','header.png','human-event.json','manifest.json','publication-conditions.json','source-manifest.json'])assert.equal(await fileSha256(path.join(psBuild.bundle_directory,name)),await fileSha256(path.join(nodeBuild.bundle_directory,name)),name);const received=await verifyBundleZip({zipPath:psBuild.zip_path,expectedPackageId:f.packageValue.package_id,extractionDirectory:path.join(f.root,'node-received-ps')});assert.equal(received.state,'HANDOFF_VERIFIED');});
  await t.test('Windows PowerShell route verifies the Node deterministic ZIP', async()=>{const clean=await buildPublicationBundle({...f.builder,outputDirectory:path.join(f.root,'ps-handoff')});const extract=path.join(f.root,'ps-received');const script=`& ${q(PS_HANDOFF)} -BundleZipPath ${q(clean.zip_path)} -ExpectedPackageId ${q(f.packageValue.package_id)} -ExtractionDirectory ${q(extract)} -Mode Handoff | ConvertTo-Json -Depth 5 -Compress`;const result=JSON.parse(execFileSync('pwsh',['-NoProfile','-Command',script],{encoding:'utf8'}));assert.equal(result.state,'HANDOFF_VERIFIED');});
});
